/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package org.dejave.attica.sql.parser;

public interface SQLParserConstants {

  int EOF = 0;
  int COMMENT_LINE = 5;
  int COMMENT_BLOCK = 6;
  int INTEGER_LITERAL = 7;
  int FLOATING_POINT_LITERAL = 8;
  int EXPONENT = 9;
  int STRING_LITERAL = 10;
  int ALL = 11;
  int AND = 12;
  int OR = 13;
  int NOT = 14;
  int SELECT = 15;
  int FROM = 16;
  int WHERE = 17;
  int ORDER = 18;
  int GROUP = 19;
  int MAX = 20;
  int MIN = 21;
  int HAVING = 22;
  int DISTINCT = 23;
  int IN = 24;
  int EXISTS = 25;
  int COUNT = 26;
  int ASC = 27;
  int DESC = 28;
  int SUM = 29;
  int BY = 30;
  int BETWEEN = 31;
  int CREATE = 32;
  int INSERT = 33;
  int TABLE = 34;
  int VALUES = 35;
  int INTO = 36;
  int DROP = 37;
  int DESCRIBE = 38;
  int CATALOG = 39;
  int DOT = 40;
  int COMMA = 41;
  int LESS = 42;
  int LESSEQUAL = 43;
  int GREATER = 44;
  int GREATEREQUAL = 45;
  int EQUAL = 46;
  int NOTEQUAL = 47;
  int NOTEQUAL2 = 48;
  int OPENPAR = 49;
  int CLOSEPAR = 50;
  int ASTERISK = 51;
  int SLASH = 52;
  int PLUS = 53;
  int MINUS = 54;
  int QUESTIONMARK = 55;
  int PERCENT = 56;
  int INTEGER = 57;
  int LONG = 58;
  int CHAR = 59;
  int BYTE = 60;
  int SHORT = 61;
  int DOUBLE = 62;
  int FLOAT = 63;
  int STRING = 64;
  int ID = 65;
  int LETTER = 66;
  int DIGIT = 67;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT_LINE>",
    "<COMMENT_BLOCK>",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"all\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"order\"",
    "\"group\"",
    "\"max\"",
    "\"min\"",
    "\"having\"",
    "\"distinct\"",
    "\"in\"",
    "\"exists\"",
    "\"count\"",
    "\"asc\"",
    "\"desc\"",
    "\"sum\"",
    "\"by\"",
    "\"between\"",
    "\"create\"",
    "\"insert\"",
    "\"table\"",
    "\"values\"",
    "\"into\"",
    "\"drop\"",
    "\"describe\"",
    "\"catalog\"",
    "\".\"",
    "\",\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"?\"",
    "\"%\"",
    "\"integer\"",
    "\"long\"",
    "\"character\"",
    "\"byte\"",
    "\"short\"",
    "\"double\"",
    "\"float\"",
    "\"string\"",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
  };

}
